### ISSUE TITLE
Approval for NPM release 0.1.0

### ISSUE THREAD

**Issue by carterm** [cagov/wordpress-to-github#109]
Release info here...
https://github.com/cagov/wordpress-to-github/releases/tag/0.1.0

(Engineers can comment with their concerns and then remove their assignment)

**Comment by carterm** [comment]
Publish beta release with `npm publish --tag beta --access public`?

**Comment by carterm** [comment]
Beta release here...
https://www.npmjs.com/package/@cagov/wordpress-to-github/v/0.1.0

**Comment by xjensen** [comment]
Looks good to me.

**Comment by zakiya** [comment]
I think it's fine for release. My suggestion would be to add clarity around **Sample output** section.  My suggestion would be Something along the line of `These are examples of the types of files that will be written to the target GitHub repo (such as drought.ca.gov) by this service.`

**Comment by carterm** [comment]
> I think it's fine for release. My suggestion would be to add clarity around **Sample output** section. My suggestion would be Something along the line of `These are examples of the types of files that will be written to the target GitHub repo (such as drought.ca.gov) by this service.`

Added to 0.2.0 release.
https://github.com/cagov/wordpress-to-github/releases/tag/0.2.0

**Comment by carterm** [comment]
0.2.0 beta released...https://github.com/cagov/wordpress-to-github/releases/tag/0.2.0
