### ISSUE TITLE
Option to hide "author" data.

### ISSUE THREAD

**Issue by chachasikes** [cagov/wordpress-to-github#111]
The 
https://dev-cagov-dcc.pantheonsite.io/wp-json/wp/v2/users is exposed and includes email addresses and this is not recommended for security reasons.

Wordpress to github IS using "users" data, but we want to not use it.

**Comment by carterm** [comment]
Highly speculative.  No evidence this is an issue.

**Comment by carterm** [comment]
If this is implemented, there should be an option to disable the author field by project.

**Comment by carterm** [comment]
Email is not exposed.  The “edit” context requires authentication to the the email.  the “view” and “embed” context are limited.
https://developer.wordpress.org/rest-api/reference/users/
