### ISSUE TITLE
meta refs to Wordpress should be document specific

### ISSUE THREAD

**Issue by carterm** [cagov/wordpress-to-github#40]
The meta fields should include precise links to return a single record (both display and API), instead of just a link to the list services.

JSON results are including links back to the root API link, and not idempotent links.

```
{
  "meta": {

    "api_url": "https://live-drought-ca-gov.pantheonsite.io/wp-json/wp/v2/",
```

should be
```
{
  "meta": {

    "api_url": "https://live-drought-ca-gov.pantheonsite.io/wp-json/wp/v2/posts/12345",
```

**Comment by chachasikes** [comment]
What's this? @carterm

**Comment by carterm** [comment]
> What's this? @carterm

Added better description.

**Comment by carterm** [comment]
https://github.com/cagov/wordpress-to-github/pull/98

**Comment by carterm** [comment]
Accidental merge
