### ISSUE TITLE
Option to add custom endpoints

### ISSUE THREAD

**Issue by carterm** [cagov/wordpress-to-github#50]
Code here pulling menus from drought...
https://github.com/cagov/drought.ca.gov/blob/main/src/templates/_data/menus.js

Need a way to tell the service to pull custom endpoint data and put it in a desired location.

Endpoint list for a WP site can be obtained here...
https://live-drought-ca-gov.pantheonsite.io/wp-json

Sample input...
https://live-drought-ca-gov.pantheonsite.io/wp-json/menus/v1/menus

**Comment by xjensen** [comment]
This will be addressed by the work in PR #91.

**Comment by carterm** [comment]
This is done thanks to the add menus PR #91 .
