### ISSUE TITLE
Connect local error output to debugger

### ISSUE THREAD

**Issue by chachasikes** [cagov/wordpress-to-github#52]
We noticed a discrepancy that some sites that have configuration issues do not output errors to the debugger. 
They are probably only connected to the Slack output. Let's get some error handling visible locally so we can test config settings fully before pushing code, (without requiring a Slack integration.)

**Comment by chachasikes** [comment]
```
FetchError: invalid json response body at https://live-cannabis-ca-gov.pantheonsite.io/wp-login.php?redirect_to=%2F%2Fwp-json%2Fwp%2Fv2%2Fmedia%3Fper_page%3D1%26orderby%3Dmodified%26order%3Ddesc%26_fields%3Dmodified%26cachebust%3D0.9595892284113481 reason: Unexpected token < in JSON at position 0
    at /home/site/wwwroot/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async WpApi_GetCacheItem_ByObjectType (/home/site/wwwroot/wordpress-to-github/common/index.js:167:39)
    at async SyncEndpoint (/home/site/wwwroot/wordpress-to-github/index.js:80:27)
    at async doProcessEndpoints (/home/site/wwwroot/WordpressSync/index.js:44:5)
    at async module.exports (/home/site/wwwroot/WordpressSync/index.js:33:5)
```

Request:
```
{
  "invocationId": "ea97656f-249d-4794-8efd-6fe238abb115",
  "traceContext": {
    "traceparent": "00-934160faec65394089fd203f66dad404-c2258a443c2f9c40-00",
    "tracestate": "",
    "attributes": {
      "OperationName": "WordpressSync"
    }
  },
  "executionContext": {
    "invocationId": "ea97656f-249d-4794-8efd-6fe238abb115",
    "functionName": "WordpressSync",
    "functionDirectory": "/home/site/wwwroot/WordpressSync",
    "retryContext": null
  },
  "bindings": {
    "WordpressSync": {
      "schedule": {
        "adjustForDST": true
      },
      "scheduleStatus": {
        "last": "2021-10-05T17:06:00.0053451+00:00",
        "next": "2021-10-05T17:08:00+00:00",
        "lastUpdated": "2021-10-05T17:06:00.0053451+00:00"
      },
      "isPastDue": false
    }
  },
  "bindingData": {
    "invocationId": "ea97656f-249d-4794-8efd-6fe238abb115",
    "timerTrigger": "10/05/2021 17:08:00"
  },
  "bindingDefinitions": [
    {
      "name": "WordpressSync",
      "type": "timerTrigger",
      "direction": "in"
    }
  ]
}```


Data
```
{
  "schedule": {
    "adjustForDST": true
  },
  "scheduleStatus": {
    "last": "2021-10-05T17:06:00.0053451+00:00",
    "next": "2021-10-05T17:08:00+00:00",
    "lastUpdated": "2021-10-05T17:06:00.0053451+00:00"
  },
  "isPastDue": false
}
```

**Comment by chachasikes** [comment]
Can't recreate this error (pointing to the login page)

The issue was that there was a trailing slash in wordpress_source_url. That needs to be handled in docs.

Couple of notes:
* Noticing that there is not a error wrapper on `wordpress-to-github/index.js` > `SyncEndpoint` > 'const data = await fetchResponse.json();'  - this should throw a specific error if it fails.
* Also this script does not need to fail completely if a service has an error. With judicious error handling, we can report errors to Slack or other logs, and skip the service.

**Comment by chachasikes** [comment]
@carterm Tagging you on this. What are your thoughts on error handling for this project?

For debugging
This branch: https://github.com/cagov/wordpress-to-github/pull/new/task-52/add-console-log-debug-mode
* Adds some debug message handling
* Can you take a look at `fetchResponse.json()` to make sure the function can break out of the cycle & move on the the next issue (but still report a message)? 
* Includes an idea about separating error message from the service it is delivering  - you could get Slack as a type & send info off to a Slack method. This would help us separate out to deliver messages to Teams, or a log file, or just the console log when debugging.

**Comment by carterm** [comment]
I think this might be a vscode config issue, because I'm seeing plenty of local errors when debugging bad urls.          `"enabledLocal": true`,  is used for local dev while `"enabled": true, `is ignored.

**Comment by carterm** [comment]
Adding new issue to address skipping errors during processing. - https://github.com/cagov/wordpress-to-github/issues/70

**Comment by carterm** [comment]
I don't have a way to reproduce this.  I'm not sure what's not working here.  Ok to close?
