### ISSUE TITLE
endpoints.json target structure

### ISSUE THREAD

**Issue by chachasikes** [cagov/wordpress-to-github#54]
@carterm would be great to change the config structure. Was looking at this & see a few issues & would like to find out our plans with how this configuration needs to grow.

This is our current structure
```
"github_targets": [
        "outputBranch": "main",
        "disabled": false,
        "PostPath": "pages/wordpress/posts",
        "PagePath": "pages/wordpress/pages",
        "MediaPath": "wordpress/media",
        "ExcludeProperties": [
          "content",
          "_links"
        ],
        "tags_exclude": []
]
```

What are we trying to configure?

**Comment by chachasikes** [comment]
For example, I drafted this:

```

```
"github_targets": [
        "outputBranch": "main",
        "disabled": false,
        "posts": {
            sourceEndpoint: "https://live-cannabis-ca-gov.pantheonsite.io/wp-json/wp/posts",
            cms: "WordPress",
            cmsVariant: "ODI Pantheon",
            targetFolder: "pages/wordpress/posts",
            urlRewrites: false,
        },
        "pages": {
            sourceEndpoint: "https://live-cannabis-ca-gov.pantheonsite.io/wp-json/wp/pages",
            cms: "WordPress",
            cmsVariant: "ODI Pantheon",
            targetFolder: "pages/wordpress/pages",
            urlRewrites: false,
        },
        "media": {
            sourceEndpoint: "https://live-cannabis-ca-gov.pantheonsite.io/wp-json/wp/media",
            cms: "WordPress",
            cmsVariant: "ODI Pantheon",
            targetFolder: "wordpress/media",
            urlRewrites: [
                {
                    string: "https://live-cannabis-ca-gov.pantheonsite.io/wp-content/uploads"
                    replacement: "/wp-content/uploads",
                }
            ], 
        }
        "ExcludeProperties": [
          "content",
          "_links"
        ],
        "tags_exclude": [],
        "tags_include": [],
]
```

Differences:
* cms & cmsVariant - This is a longer term goal, but how will we support other CMSs? A lot of this is the same - hitting endpoints & storing data. We will probably start trying some new CMSs in a month or so as we start to ensure the data model still renders for all the design system components.
* `urlRewrites` - for content type specific rewriting - imagine media folder gets moved to s3 & that the endpoints move to another service.


Here's a sketch for menus cc @xjensen 

```
      "menu": {
            sourceEndpoint: "https://live-drought-ca-gov.pantheonsite.io/wp-json/menus/v1/menus",
            cms: "WordPress",
            cmsVariant: "Core Wordpress",
            targetFolder: "wordpress/menu",
            urlRewrites: false, 
        },
        "redirects": {
            sourceEndpoint: "https://live-drought-ca-gov.pantheonsite.io/wp-json/redirection/v1", // I forgot the exact endpoint
            cms: "WordPress",
            cmsVariant: "Core Wordpress",
            targetFolder: "wordpress/menu",
            urlRewrites: false, 
        },
```

Thoughts?

**Comment by carterm** [comment]
I like where this is going.  I want to find a way to separate connection/communication from function.  The folder structure and rewrites are function, while the branch name and endpoints are communication.

**Comment by carterm** [comment]
Should also include slack channel in config.
https://github.com/cagov/wordpress-to-github/issues/37

**Comment by carterm** [comment]
A figma board or some other visual architecture design would be great for this.
