### ISSUE TITLE
When and how do we split up our wordpress-to-github services?

### ISSUE THREAD

**Issue by chachasikes** [cagov/wordpress-to-github#77]
Our team just met in Slack huddles.

We discussed:
- naming conventions for our middleware microservices
- some folder & yml structures that might make sense

Goal:
- Keep services stable & mapped to a tagged release of wordpress to github
- Be able to control when upgrades happen (so that changes can be communicated to editorial teams if necessary, or planned updates during quiet traffic times & not during an important content update)
- Be able to test the services without effecting other services
- Be able to find them quickly
- Be able to group services in a way that makes sense
- Be able to find the repo / microservice instance easily if we need to maintain the service (with names that are clear)
- (Anything else?)

**Comment by carterm** [comment]
The services are all split up.  Now this issue is about the overall deployment strategy.

**Comment by chachasikes** [comment]
Closing. One issue / One idea.
