### ISSUE TITLE
Add tags for releases

### ISSUE THREAD

**Issue by chachasikes** [cagov/wordpress-to-github#78]
Zakiya requested that we use at least the tagging feature of Git to give names to different versions of code until we are ready to do formal releases.

We can
* start a CHANGELOG and ROADMAP file in the repo to communicate what is different from tag to tag (@kkoryaka has been rocking the CHANGELOGs for the design system)
* use semantic versioning (1.0.0, 1.0.1) patterns like we are for our npm packages and wordpress plugin and CAWeb.
* Q for Carter... is this version 3.0.0 (alpha: 1.x.x, covid: 2.x.x, scaling up phase 1 3.x.x) - other structural differences can have their own appropriate point releases
* For filling in old changelog, you can do summaries - just the gist of what happened is helpful for new developers to understand the context.

Action item: 
- Pick an upcoming commit & give it a tag
- Tell Zakiya which tag it is

**Comment by carterm** [comment]
Tags exist!

https://github.com/cagov/wordpress-to-github/releases/tag/0.0.2
