### ISSUE TITLE
Discuss `wordpress/general/general.json`

### ISSUE THREAD

**Issue by chachasikes** [cagov/wordpress-to-github#85]
* Do we need it?
* Can we gitignore it?
* Did you know if you change the path that it will delete folders?

**Comment by carterm** [comment]
All good @zakiya ?

**Comment by carterm** [comment]
Also...https://github.com/cagov/wordpress-to-github/issues/96

**Comment by zakiya** [comment]
Summary: 

`general.json` is  a file with global values from the source WordPress database such as site name, site description, and url. The wordpress-to-github service writes this file to the target GitHub repository (such as drought.ca.gov) so these values are available to the static site generator. 

I'm no longer blocked so we can close this.
